language: python

compiler: g++

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 40 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --config gcc

install:
    # installing  requirements for kattis problem tools
    # note that on debian/ubuntu pip tools are being installed to the python2 pip
    # install kattis problem tools
    - chmod +x travis-install.sh
    - sudo ./travis-install.sh
    - sudo pip2 install git+https://github.com/kattis/problemtools


script:
    - verifyproblem armorhere
    - verifyproblem craftmines
    - verifyproblem dangtiles
    - verifyproblem melzarmaze
    - verifyproblem silentmist
    - verifyproblem slaykayran
    - verifyproblem standbehindbraum
    - verifyproblem thewayforward
